#!/bin/sh

cd ${0%/*} || exit 1

. $WM_PROJECT_DIR/bin/tools/RunFunctions

rm -rf constant/polyMesh/sets

#runApplication blockMesh
#runApplication snappyHexMesh -overwrite
ideasUnvToFoam Mesh_1.unv
transformPoints -scale "(1e-3 1e-3 1e-3)"
runApplication splitMeshRegions -cellZones -overwrite
runApplication decomposePar -allRegions
runParallel $(getApplication)
runApplication reconstructPar -allRegions
#paraFoam -touchAll
touch simpleSample.foam
